services:
  - type: web
    name: ibnaa-ras-isa
    runtime: node
    plan: free
    buildCommand: cd client && npm install && npm run build && cd ../server && npm install
    startCommand: cd server && node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: GMAIL_USER
        sync: false
      - key: GMAIL_PASS
        sync: false